name: Lint

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
