name: Lint CSS

on:
  push:
    paths:
      - '**/*.css'
      - '**/*.scss'
      - '.github/workflows/lint-css.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Lint CSS
        run: npm run lint:css